pipeline {
    agent any
       tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
    stages {
        stage('Build 2') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}