pipeline {
    agent any
       tools { 
        maven 'Maven' 
    }
    stages {
    //     stage('Build ') { 
    //         steps {
    //             sh 'pwd'
    //             sh 'mvn -f cidr_convert_api/java/cidr-api/pom.xml clean install -e'
    //             //sh 'mvn -B -DskipTests cidr_convert_api/java/cidr-api/pom.xml clean package' 
    //         }
    //     }
        
        stage("build & SonarQube analysis") {
            agent any
            steps {
              withSonarQubeEnv('Sonar') {
               // sh 'dir(cidr_convert_api/java/cidr-api)'
              //  sh 'mvn -f cidr_convert_api/java/cidr-api/pom.xml  sonar:sonar'
                sh 'mvn -f cidr_convert_api/java/cidr-api/ org.sonarsource.scanner.maven:sonar-maven-plugin:4.7.0.2747:sonar'
               // sh 'mvn -f cidr_convert_api/java/cidr-api/pom.xml org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar '
              }
            }
          }

          stage('Checkout') {
      steps {
        script {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], userRemoteConfigs: [[url: 'https://github.com/OctopusSamples/RandomQuotes-Java.git']]])
        }
      }
    }
    stage('Test') {
      steps {
        sh(script: './mvnw --batch-mode -Dmaven.test.failure.ignore=true test')

      }
    }
    stage('Package') {
      steps {
        sh(script: './mvnw --batch-mode package -DskipTests')
      }
    }
 
    
}
 
  post {
    always {
      junit(testResults: 'target/surefire-reports/*.xml', allowEmptyResults : true)
    }
    }
}