pipeline {
   agent any
    stages {
        stage('Build') { 
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}